# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Jekyll exercice"
description: "Jekyll exercice"

# Build settings
markdown: kramdown

# Collections
collections:
  posts:
    output: true
  work:
    output: true

# Yaml default
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post_detail
      current_section: blog
  -
    scope:
      path: ""
      type: work
    values:
      layout: work_detail
      current_section: work
